apiVersion: v1
kind: BuildConfig
metadata:
  name: java-sdk-openjdk
spec:
  triggers:
    - type: ConfigChange
    - type: imageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: java-openjdk:latest
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/section6nz/openshift-java-sdk-openjdk.git'
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: java-openjdk:latest
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: 'java-sdk-openjdk:latest'